# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: aaa33036311a0b88d49541382b2e1b2828ee2fd5d860757481e7d20bad1dbd1b0fb13ad725635329c2c49663ab9899113497187f54c84dc159c32c4bb892b0a4
  google_storage_access_key_id: "GOOGNJDB7NCWOTKRZEF3555T"
  google_storage_secret_access_key: "eNeE/Nw23qvCMLkPeYbiGdySvY7TvdYPSm+GEf5e"
  google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  google_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>

test:
  secret_key_base: 1836a566141556d9cdb8c6de0ec8caac0cc53a5d81ec12a3e9a282ec009301e2893012e4e97cec36d9926f6b62b13e6e503eef4904ffbdbe0c17814d02487e00
  google_storage_access_key_id: "some value"
  google_storage_secret_access_key: "some value"
# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_storage_access_key_id: <%= ENV["GOOGLE_STORAGE_ACCESS_KEY_ID"] %>
  google_storage_secret_access_key: <%= ENV["GOOGLE_STORAGE_SECRET_ACCESS_KEY"] %>
